---
- name: Install Zabbix Agent 2
  hosts: all
  become: true

  vars:
    zabbix_agent2_conf: "/etc/zabbix/zabbix_agent2.conf"
    zabbix_server_ip: "192.168.0.1"  # IP  Zabbix сервера
    zabbix_version: "6.0" 

  tasks:
      - name: Add repo for Ubuntu/Debian OS
        apt:
          deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_facts['distribution'] | lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-2+{{ ansible_facts['distribution'] | lower }}{{ ansible_facts['distribution_version'] }}_all.deb"
          state: present

      - name: Update apt cache
        apt:
          update_cache: yes

      - name: Install Zabbix Agent 2
        apt:
          name: zabbix-agent2
          state: present

      - name: Configure Zabbix Agent 2
        lineinfile:
          path: "{{ zabbix_agent2_conf }}"
          regexp: "^Server="
          line: "Server={{ zabbix_server_ip }}"
          backup: yes